# Generated by Django 3.0.8 on 2020-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='pics/'),
        ),
    ]
