# Generated by Django 3.0.8 on 2020-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200722_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='UserName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
