# Generated by Django 3.0.8 on 2020-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_auto_20200722_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='photo',
            field=models.ImageField(blank=True, default='VoteMe/static/user.jpg', null=True, upload_to='users/'),
        ),
    ]
