# Generated by Django 3.0.8 on 2020-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_auto_20200722_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='photo',
            field=models.URLField(),
        ),
    ]
