# Generated by Django 3.0.8 on 2020-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_auto_20200722_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='photo',
            field=models.ImageField(default='user.jpg', null=True, upload_to='user_profile/'),
        ),
    ]
