# Generated by Django 3.0.8 on 2020-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0023_auto_20200722_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='photo',
            new_name='Profile_Pic',
        ),
    ]
