# Generated by Django 3.0.8 on 2020-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_auto_20200722_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Profile_Pic', models.ImageField(default='user.jpg', null=True, upload_to='user_profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
