# Generated by Django 3.0.8 on 2020-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0025_auto_20200722_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_Pic',
            field=models.ImageField(default='user.jpg', upload_to='user_profile/'),
        ),
    ]
