# Generated by Django 3.0.8 on 2020-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0028_auto_20200723_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_Pic',
            field=models.FileField(default='user.jpg', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
