# Generated by Django 3.0.8 on 2020-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0029_auto_20200723_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_Pic',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
