# Generated by Django 3.0.8 on 2020-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0030_auto_20200723_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Profile_Pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Profile_Photo',
            field=models.FileField(default='user.jpg', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
