# Generated by Django 3.0.8 on 2020-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0031_auto_20200723_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_Photo',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
