# Generated by Django 3.0.8 on 2020-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0036_auto_20200723_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Profile_Image', models.ImageField(null=True, upload_to='Profile_Image')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
