# Generated by Django 3.0.8 on 2020-07-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0037_auto_20200723_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
