# Generated by Django 3.0.8 on 2020-07-25 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0040_auto_20200724_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('SName', models.CharField(max_length=50)),
                ('CN', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PartName', models.CharField(max_length=50)),
                ('Profile_Image', models.ImageField(default='user.jpg', upload_to='Leader_Image')),
                ('Name', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
