# Generated by Django 3.0.8 on 2020-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0041_candidatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedata',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
