# Generated by Django 3.0.8 on 2020-07-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0044_candidatedata_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedata',
            name='Profile_Image',
        ),
    ]
