# Generated by Django 3.0.8 on 2020-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0045_remove_candidatedata_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedata',
            name='Profile_Image',
            field=models.ImageField(default='user.jpg', upload_to='Profile_Image'),
        ),
    ]
