# Generated by Django 3.0.8 on 2020-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0047_candidatedata_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedata',
            name='Vote',
            field=models.IntegerField(default=0),
        ),
    ]
