# Generated by Django 3.0.8 on 2020-07-14 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates_details',
            fields=[
                ('LeaderNo', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('LeaderName', models.CharField(max_length=50)),
                ('Political_Party', models.CharField(max_length=50)),
                ('Leader_Image', models.ImageField(null=True, upload_to='Leader_Image')),
                ('Votes_got', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Voting_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('LeaderName', models.CharField(max_length=50)),
                ('Political_Party', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vote_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_Of_Votes_You_Cast', models.IntegerField(blank=True, default=0)),
                ('UserName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.BooleanField(default=False)),
                ('UserName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
