# Generated by Django 3.0.8 on 2020-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0007_reply_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Message',
            new_name='Query',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='Message',
            new_name='Reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='Query',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
