# Generated by Django 3.0.8 on 2020-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0009_auto_20200716_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft_Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Query', models.TextField(max_length=300)),
            ],
        ),
    ]
