# Generated by Django 3.0.8 on 2020-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0010_draft_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='UserName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote_count',
            name='UserName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
