# Generated by Django 3.0.8 on 2020-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0011_auto_20200720_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
