# Generated by Django 3.0.8 on 2020-07-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0016_auto_20200721_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='img',
            new_name='pimg',
        ),
    ]
