# Generated by Django 3.0.8 on 2020-07-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVM', '0017_auto_20200721_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
